version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_USER=$MYSQLDB_USER
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    # command: env
  api:
    depends_on:
      - mariadb
    build: ./API
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    environment:
      - DB_HOST=mariadb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  imagery:
    depends_on:
      - api
    build: ./ImageService
    env_file: ./.env
    ports:
      - $IMAGE_LOCAL_PORT:$IMAGE_DOCKER_PORT
    environment:
      - DOCKER_PORT=$IMAGE_DOCKER_PORT
  front:
    build: ./front
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $FRONT_LOCAL_PORT:$FRONT_DOCKER_PORT
volumes:
  db:

